require 'option'
require 'mapping'
require 'autocmd'
require 'lazy-setup'
-- require 'plugins.treesitter'
-- require 'plugins.lsp'
-- require 'plugins.autocomplete'
-- require 'plugins.lua-formatter'
-- require 'plugins.autoformat'
-- require 'plugins.gitsigns'
-- require 'plugins.autopairs'
-- require 'plugins.telescope'
-- require 'plugins.colorscheme'
-- require 'plugins.miniai'
-- require 'plugins.todo'
-- require 'plugins.whichkey'
-- require 'plugins.debug'
-- require 'plugins.nvim-colorizer'
